export const data = {
  code: "8901725016296",
  product: {
    _id: "8901725016296",
    _keywords: [
      "and",
      "biscuit",
      "bourbon",
      "cake",
      "dark",
      "fantasy",
      "snack",
      "sunfeast",
      "sweet",
    ],
    added_countries_tags: [],
    additives_n: 9,
    allergens_hierarchy: ["en:gluten", "en:milk", "en:soybeans"],

    amino_acids_tags: [],
    brands: "Sunfeast",
    brands_tags: ["sunfeast"],
    categories: "Snacks, Sweet snacks, Biscuits and cakes, Biscuits",
    categories_hierarchy: [
      "en:snacks",
      "en:sweet-snacks",
      "en:biscuits-and-cakes",
      "en:biscuits",
    ],
    categories_lc: "en",
    categories_old: "biscuit",
    categories_properties: {
      "agribalyse_proxy_food_code:en": "24000",
    },

    categories_tags: [
      "en:snacks",
      "en:sweet-snacks",
      "en:biscuits-and-cakes",
      "en:biscuits",
    ],

    compared_to_category: "en:biscuits",
    complete: 0,
    completeness: 0.675,
    correctors_tags: ["krishanti", "dranujbarot"],
    countries: "India",
    countries_hierarchy: ["en:india"],
    countries_lc: "en",
    countries_tags: ["en:india"],
    created_t: 1707364085,
    creator: "krishanti",
    data_quality_bugs_tags: [],
    data_quality_errors_tags: [],
    data_quality_info_tags: [
      "en:no-packaging-data",
      "en:ingredients-percent-analysis-ok",
      "en:environmental-score-extended-data-not-computed",
      "en:food-groups-1-known",
      "en:food-groups-2-known",
      "en:food-groups-3-unknown",
    ],
    data_quality_tags: [
      "en:no-packaging-data",
      "en:ingredients-percent-analysis-ok",
      "en:environmental-score-extended-data-not-computed",
      "en:food-groups-1-known",
      "en:food-groups-2-known",
      "en:food-groups-3-unknown",
      "en:environmental-score-origins-of-ingredients-origins-are-100-percent-unknown",
      "en:environmental-score-packaging-packaging-data-missing",
      "en:environmental-score-production-system-no-label",
    ],
    data_quality_warnings_tags: [
      "en:environmental-score-origins-of-ingredients-origins-are-100-percent-unknown",
      "en:environmental-score-packaging-packaging-data-missing",
      "en:environmental-score-production-system-no-label",
    ],
    data_sources: "App - smoothie-openfoodfacts, Apps",
    data_sources_tags: ["app-smoothie-openfoodfacts", "apps"],
    debug_param_sorted_langs: ["en"],
    ecoscore_data: {
      adjustments: {
        origins_of_ingredients: {
          aggregated_origins: [
            {
              epi_score: 0,
              origin: "en:unknown",
              percent: 100,
              transportation_score: 0,
            },
          ],
          epi_score: 0,
          epi_value: -5,
          origins_from_categories: ["en:unknown"],
          origins_from_origins_field: ["en:unknown"],
          transportation_score: 0,
          transportation_scores: {
            ad: 0,
            al: 0,
            at: 0,
            ax: 0,
            ba: 0,
            be: 0,
            bg: 0,
            ch: 0,
            cy: 0,
            cz: 0,
            de: 0,
            dk: 0,
            dz: 0,
            ee: 0,
            eg: 0,
            es: 0,
            fi: 0,
            fo: 0,
            fr: 0,
            gg: 0,
            gi: 0,
            gr: 0,
            hr: 0,
            hu: 0,
            ie: 0,
            il: 0,
            im: 0,
            is: 0,
            it: 0,
            je: 0,
            lb: 0,
            li: 0,
            lt: 0,
            lu: 0,
            lv: 0,
            ly: 0,
            ma: 0,
            mc: 0,
            md: 0,
            me: 0,
            mk: 0,
            mt: 0,
            nl: 0,
            no: 0,
            pl: 0,
            ps: 0,
            pt: 0,
            ro: 0,
            rs: 0,
            se: 0,
            si: 0,
            sj: 0,
            sk: 0,
            sm: 0,
            sy: 0,
            tn: 0,
            tr: 0,
            ua: 0,
            uk: 0,
            us: 0,
            va: 0,
            world: 0,
            xk: 0,
          },
          transportation_value: 0,
          transportation_values: {
            ad: 0,
            al: 0,
            at: 0,
            ax: 0,
            ba: 0,
            be: 0,
            bg: 0,
            ch: 0,
            cy: 0,
            cz: 0,
            de: 0,
            dk: 0,
            dz: 0,
            ee: 0,
            eg: 0,
            es: 0,
            fi: 0,
            fo: 0,
            fr: 0,
            gg: 0,
            gi: 0,
            gr: 0,
            hr: 0,
            hu: 0,
            ie: 0,
            il: 0,
            im: 0,
            is: 0,
            it: 0,
            je: 0,
            lb: 0,
            li: 0,
            lt: 0,
            lu: 0,
            lv: 0,
            ly: 0,
            ma: 0,
            mc: 0,
            md: 0,
            me: 0,
            mk: 0,
            mt: 0,
            nl: 0,
            no: 0,
            pl: 0,
            ps: 0,
            pt: 0,
            ro: 0,
            rs: 0,
            se: 0,
            si: 0,
            sj: 0,
            sk: 0,
            sm: 0,
            sy: 0,
            tn: 0,
            tr: 0,
            ua: 0,
            uk: 0,
            us: 0,
            va: 0,
            world: 0,
            xk: 0,
          },
          value: -5,
          values: {
            ad: -5,
            al: -5,
            at: -5,
            ax: -5,
            ba: -5,
            be: -5,
            bg: -5,
            ch: -5,
            cy: -5,
            cz: -5,
            de: -5,
            dk: -5,
            dz: -5,
            ee: -5,
            eg: -5,
            es: -5,
            fi: -5,
            fo: -5,
            fr: -5,
            gg: -5,
            gi: -5,
            gr: -5,
            hr: -5,
            hu: -5,
            ie: -5,
            il: -5,
            im: -5,
            is: -5,
            it: -5,
            je: -5,
            lb: -5,
            li: -5,
            lt: -5,
            lu: -5,
            lv: -5,
            ly: -5,
            ma: -5,
            mc: -5,
            md: -5,
            me: -5,
            mk: -5,
            mt: -5,
            nl: -5,
            no: -5,
            pl: -5,
            ps: -5,
            pt: -5,
            ro: -5,
            rs: -5,
            se: -5,
            si: -5,
            sj: -5,
            sk: -5,
            sm: -5,
            sy: -5,
            tn: -5,
            tr: -5,
            ua: -5,
            uk: -5,
            us: -5,
            va: -5,
            world: -5,
            xk: -5,
          },
          warning: "origins_are_100_percent_unknown",
        },
        packaging: {
          value: -15,
          warning: "packaging_data_missing",
        },
        production_system: {
          labels: [],
          value: 0,
          warning: "no_label",
        },
        threatened_species: {
          ingredient: "en:palm-oil",
          value: -10,
        },
      },
      agribalyse: {
        agribalyse_proxy_food_code: "24000",
        co2_agriculture: 2.3635185,
        co2_consumption: 0,
        co2_distribution: 0.019437894,
        co2_packaging: 0.10986902,
        co2_processing: 0.22831584,
        co2_total: 2.856230424,
        co2_transportation: 0.13508917,
        code: "24000",
        dqr: "2.14",
        ef_agriculture: 0.27654213,
        ef_consumption: 0,
        ef_distribution: 0.0047895045,
        ef_packaging: 0.01090994,
        ef_processing: 0.04151582,
        ef_total: 0.3448030585,
        ef_transportation: 0.011045664,
        is_beverage: 0,
        name_en: "Biscuit (cookie)",
        name_fr: "Biscuit sec, sans précision",
        score: 70,
        version: "3.1.1",
      },
      grade: "d",
      grades: {
        ad: "d",
        al: "d",
        at: "d",
        ax: "d",
        ba: "d",
        be: "d",
        bg: "d",
        ch: "d",
        cy: "d",
        cz: "d",
        de: "d",
        dk: "d",
        dz: "d",
        ee: "d",
        eg: "d",
        es: "d",
        fi: "d",
        fo: "d",
        fr: "d",
        gg: "d",
        gi: "d",
        gr: "d",
        hr: "d",
        hu: "d",
        ie: "d",
        il: "d",
        im: "d",
        is: "d",
        it: "d",
        je: "d",
        lb: "d",
        li: "d",
        lt: "d",
        lu: "d",
        lv: "d",
        ly: "d",
        ma: "d",
        mc: "d",
        md: "d",
        me: "d",
        mk: "d",
        mt: "d",
        nl: "d",
        no: "d",
        pl: "d",
        ps: "d",
        pt: "d",
        ro: "d",
        rs: "d",
        se: "d",
        si: "d",
        sj: "d",
        sk: "d",
        sm: "d",
        sy: "d",
        tn: "d",
        tr: "d",
        ua: "d",
        uk: "d",
        us: "d",
        va: "d",
        world: "d",
        xk: "d",
      },
      missing: {
        labels: 1,
        origins: 1,
        packagings: 1,
      },
      missing_data_warning: 1,
      missing_key_data: 1,
      score: 40,
      scores: {
        ad: 40,
        al: 40,
        at: 40,
        ax: 40,
        ba: 40,
        be: 40,
        bg: 40,
        ch: 40,
        cy: 40,
        cz: 40,
        de: 40,
        dk: 40,
        dz: 40,
        ee: 40,
        eg: 40,
        es: 40,
        fi: 40,
        fo: 40,
        fr: 40,
        gg: 40,
        gi: 40,
        gr: 40,
        hr: 40,
        hu: 40,
        ie: 40,
        il: 40,
        im: 40,
        is: 40,
        it: 40,
        je: 40,
        lb: 40,
        li: 40,
        lt: 40,
        lu: 40,
        lv: 40,
        ly: 40,
        ma: 40,
        mc: 40,
        md: 40,
        me: 40,
        mk: 40,
        mt: 40,
        nl: 40,
        no: 40,
        pl: 40,
        ps: 40,
        pt: 40,
        ro: 40,
        rs: 40,
        se: 40,
        si: 40,
        sj: 40,
        sk: 40,
        sm: 40,
        sy: 40,
        tn: 40,
        tr: 40,
        ua: 40,
        uk: 40,
        us: 40,
        va: 40,
        world: 40,
        xk: 40,
      },
      status: "known",
    },
    ecoscore_grade: "d",
    ecoscore_score: 40,
    ecoscore_tags: ["d"],
    editors_tags: ["dranujbarot", "foodless", "krishanti", "roboto-app"],
    emb_codes: "",
    emb_codes_tags: [],
    entry_dates_tags: ["2024-02-08", "2024-02", "2024"],
    expiration_date: "",
    food_groups: "en:biscuits-and-cakes",
    food_groups_tags: ["en:sugary-snacks", "en:biscuits-and-cakes"],
    generic_name: "",
    generic_name_en: "",
    id: "8901725016296",
    image_front_small_url:
      "https://images.openfoodfacts.net/images/products/890/172/501/6296/front_en.6.200.jpg",
    image_front_thumb_url:
      "https://images.openfoodfacts.net/images/products/890/172/501/6296/front_en.6.100.jpg",
    image_front_url:
      "https://images.openfoodfacts.net/images/products/890/172/501/6296/front_en.6.400.jpg",
    image_nutrition_small_url:
      "https://images.openfoodfacts.net/images/products/890/172/501/6296/nutrition_en.8.200.jpg",
    image_nutrition_thumb_url:
      "https://images.openfoodfacts.net/images/products/890/172/501/6296/nutrition_en.8.100.jpg",
    image_nutrition_url:
      "https://images.openfoodfacts.net/images/products/890/172/501/6296/nutrition_en.8.400.jpg",
    image_small_url:
      "https://images.openfoodfacts.net/images/products/890/172/501/6296/front_en.6.200.jpg",
    image_thumb_url:
      "https://images.openfoodfacts.net/images/products/890/172/501/6296/front_en.6.100.jpg",
    image_url:
      "https://images.openfoodfacts.net/images/products/890/172/501/6296/front_en.6.400.jpg",
    images: {
      1: {
        sizes: {
          100: {
            h: 75,
            w: 100,
          },
          400: {
            h: 300,
            w: 400,
          },
          full: {
            h: 3456,
            w: 4608,
          },
        },
        uploaded_t: 1707364085,
        uploader: "krishanti",
      },
      front_en: {
        coordinates_image_size: "full",
        imgid: "1",
        rev: "6",
        sizes: {
          100: {
            h: 34,
            w: 100,
          },
          200: {
            h: 69,
            w: 200,
          },
          400: {
            h: 137,
            w: 400,
          },
          full: {
            h: 1048,
            w: 3056,
          },
        },
        x1: 1264,
        x2: 4320,
        y1: 1183,
        y2: 2231,
      },
      nutrition_en: {
        coordinates_image_size: "full",
        imgid: "1",
        rev: "8",
        sizes: {
          100: {
            h: 16,
            w: 100,
          },
          200: {
            h: 31,
            w: 200,
          },
          400: {
            h: 63,
            w: 400,
          },
          full: {
            h: 272,
            w: 1736,
          },
        },
        x1: 1448,
        x2: 3184,
        y1: 1495,
        y2: 1767,
      },
    },
    informers_tags: ["krishanti", "roboto-app", "dranujbarot"],
    ingredients: [
      {
        ciqual_proxy_food_code: "9410",
        ecobalyse_code: "flour",
        id: "en:refined-wheat-flour",
        ingredients: [
          {
            ciqual_proxy_food_code: "9410",
            ecobalyse_code: "flour",
            id: "en:refined-wheat-flour",
            is_in_taxonomy: 1,
            percent_estimate: 40.6,
            percent_max: 48.4,
            percent_min: 32.8,
            text: "REFINED WHEAT FLOUR",
            vegan: "yes",
            vegetarian: "yes",
          },
        ],
        is_in_taxonomy: 1,
        percent_estimate: 40.6,
        percent_max: 48.4,
        percent_min: 32.8,
        text: "MAIDA",
        vegan: "yes",
        vegetarian: "yes",
      },
      {
        ciqual_proxy_food_code: "31016",
        ecobalyse_code: "sugar",
        id: "en:sugar",
        is_in_taxonomy: 1,
        percent: 32.8,
        percent_estimate: 32.8,
        percent_max: 32.8,
        percent_min: 32.8,
        text: "SUGAR",
        vegan: "yes",
        vegetarian: "yes",
      },
      {
        ciqual_food_code: "16150",
        ecobalyse_code: "refined-palm-oil",
        from_palm_oil: "yes",
        id: "en:refined-palm-oil",
        is_in_taxonomy: 1,
        percent_estimate: 10.1,
        percent_max: 17.9,
        percent_min: 2.3,
        text: "REFINED PALM OIL",
        vegan: "yes",
        vegetarian: "yes",
      },
      {
        id: "en:colour",
        is_in_taxonomy: 1,
        percent_estimate: 9.4,
        percent_max: 17.2,
        percent_min: 2.3,
        text: "COLOURS",
      },
      {
        id: "en:e150a",
        is_in_taxonomy: 1,
        percent_estimate: 4.7,
        percent_max: 10.7,
        percent_min: 2.3,
        text: "e150a",
        vegan: "yes",
        vegetarian: "yes",
      },
      {
        id: "en:e150a",
        is_in_taxonomy: 1,
        percent_estimate: 2.35,
        percent_max: 7.45,
        percent_min: 2.3,
        text: "e150c",
        vegan: "yes",
        vegetarian: "yes",
      },
      {
        id: "en:e150d",
        is_in_taxonomy: 1,
        percent_estimate: 1.175,
        percent_max: 5.5,
        percent_min: 2.3,
        text: "e150d",
        vegan: "yes",
        vegetarian: "yes",
      },
      {
        id: "en:e129",
        is_in_taxonomy: 1,
        percent_estimate: 0.5875,
        percent_max: 4.2,
        percent_min: 2.3,
        text: "e129",
        vegan: "yes",
        vegetarian: "yes",
      },
      {
        ciqual_proxy_food_code: "9510",
        id: "en:starch",
        is_in_taxonomy: 1,
        percent_estimate: 0.293749999999997,
        percent_max: 3.27142857142857,
        percent_min: 2.3,
        text: "STARCH",
        vegan: "yes",
        vegetarian: "yes",
      },
      {
        ciqual_proxy_food_code: "18100",
        id: "en:cocoa-solids",
        is_in_taxonomy: 1,
        percent: 2.3,
        percent_estimate: -2.00625000000001,
        percent_max: 2.3,
        percent_min: 2.3,
        text: "COCOA SOLIDS",
        vegan: "yes",
        vegetarian: "yes",
      },
      {
        id: "en:milk-solids-raising-agents",
        ingredients: [
          {
            id: "en:e503ii",
            is_in_taxonomy: 1,
            percent_estimate: 0.025,
            percent_max: 2.03333333333334,
            percent_min: 0,
            text: "e503ii",
            vegan: "yes",
            vegetarian: "yes",
          },
          {
            id: "en:e500ii",
            is_in_taxonomy: 1,
            percent_estimate: 0.0125,
            percent_max: 1.01666666666667,
            percent_min: 0,
            text: "e500ii",
            vegan: "yes",
            vegetarian: "yes",
          },
          {
            id: "en:e450i",
            is_in_taxonomy: 1,
            percent_estimate: 0.0125,
            percent_max: 0.766666666666667,
            percent_min: 0,
            text: "e450i",
            vegan: "yes",
            vegetarian: "yes",
          },
        ],
        is_in_taxonomy: 0,
        percent_estimate: 0.05,
        percent_max: 2.03333333333334,
        percent_min: 0.1,
        text: "MILK SOLIDS RAISING AGENTS",
      },
      {
        id: "en:artificial-flavouring",
        ingredients: [
          {
            id: "en:vanilla",
            is_in_taxonomy: 1,
            percent_estimate: 0.0125000000000007,
            percent_max: 1.82,
            percent_min: 0,
            text: "VANILLA",
            vegan: "yes",
            vegetarian: "yes",
          },
          {
            id: "en:chocolate",
            is_in_taxonomy: 1,
            percent_estimate: 0.0125000000000007,
            percent_max: 0.910000000000002,
            percent_min: 0,
            text: "CHOCOLATE",
            vegan: "maybe",
            vegetarian: "yes",
          },
        ],
        is_in_taxonomy: 1,
        percent_estimate: 0.0250000000000014,
        percent_max: 1.82,
        percent_min: 0.1,
        text: "ARTIFICIAL FLAVOURING SUBSTANCES",
        vegan: "maybe",
        vegetarian: "maybe",
      },
      {
        id: "en:emulsifier",
        ingredients: [
          {
            from_palm_oil: "maybe",
            id: "en:e471",
            ingredients: [
              {
                ciqual_food_code: "16129",
                ecobalyse_code: "refined-palm-oil",
                from_palm_oil: "yes",
                id: "en:palm-oil",
                is_in_taxonomy: 1,
                percent_estimate: 0.00624999999999929,
                percent_max: 1.64545454545455,
                percent_min: 0,
                text: "FROM PALM OIL",
                vegan: "yes",
                vegetarian: "yes",
              },
            ],
            is_in_taxonomy: 1,
            percent_estimate: 0.00624999999999929,
            percent_max: 1.64545454545455,
            percent_min: 0,
            text: "mono- and DIGLYCERIDES OF FATTY ACIDS",
            vegan: "maybe",
            vegetarian: "maybe",
          },
          {
            id: "en:e322i",
            ingredients: [
              {
                id: "en:from-soyabean",
                is_in_taxonomy: 0,
                percent_estimate: 0.00624999999999929,
                percent_max: 0.822727272727275,
                percent_min: 0,
                text: "FROM SOYABEAN",
              },
            ],
            is_in_taxonomy: 1,
            percent_estimate: 0.00624999999999929,
            percent_max: 0.822727272727275,
            percent_min: 0,
            text: "LECITHIN",
            vegan: "maybe",
            vegetarian: "maybe",
          },
        ],
        is_in_taxonomy: 1,
        percent_estimate: 0.0124999999999986,
        percent_max: 1.64545454545455,
        percent_min: 0.1,
        text: "EMULSIFIERS",
      },
      {
        ciqual_proxy_food_code: "31074",
        ecobalyse_code: "dark-chocolate",
        id: "en:dark-chocolate",
        is_in_taxonomy: 1,
        percent: 0.1,
        percent_estimate: -0.0875000000000057,
        percent_max: 0.1,
        percent_min: 0.1,
        text: "PLAIN CHOCOLATE",
        vegan: "maybe",
        vegetarian: "yes",
      },
      {
        ciqual_food_code: "11058",
        id: "en:iodised-salt",
        is_in_taxonomy: 1,
        percent_estimate: 0,
        percent_max: 0.1,
        percent_min: 0,
        text: "IODIZED SALT",
        vegan: "yes",
        vegetarian: "yes",
      },
      {
        id: "en:nature-identical-flavouring",
        ingredients: [
          {
            id: "en:chocolate",
            is_in_taxonomy: 1,
            percent_estimate: 0,
            percent_max: 0.1,
            percent_min: 0,
            text: "CHOCOLATE",
            vegan: "maybe",
            vegetarian: "yes",
          },
        ],
        is_in_taxonomy: 1,
        percent_estimate: 0,
        percent_max: 0.1,
        percent_min: 0,
        text: "NATURE IDENTICAL FLAVOURING SUBSTANCES",
        vegan: "maybe",
        vegetarian: "maybe",
      },
    ],
    ingredients_analysis: {
      "en:palm-oil": ["en:refined-palm-oil", "en:palm-oil"],
      "en:vegan-status-unknown": [
        "en:milk-solids-raising-agents",
        "en:from-soyabean",
      ],
      "en:vegetarian-status-unknown": [
        "en:milk-solids-raising-agents",
        "en:from-soyabean",
      ],
    },
    ingredients_analysis_tags: [
      "en:palm-oil",
      "en:vegan-status-unknown",
      "en:vegetarian-status-unknown",
    ],
    ingredients_from_or_that_may_be_from_palm_oil_n: 0,
    ingredients_from_palm_oil_n: 0,
    ingredients_from_palm_oil_tags: [],
    ingredients_hierarchy: [
      "en:refined-wheat-flour",
      "en:cereal",
      "en:flour",
      "en:wheat",
      "en:cereal-flour",
      "en:wheat-flour",
      "en:sugar",
      "en:added-sugar",
      "en:disaccharide",
      "en:refined-palm-oil",
      "en:oil-and-fat",
      "en:vegetable-oil-and-fat",
      "en:palm-oil-and-fat",
      "en:palm-oil",
      "en:colour",
      "en:e150a",
      "en:e150d",
      "en:e129",
      "en:starch",
      "en:cocoa-solids",
      "en:plant",
      "en:cocoa",
      "en:milk-solids-raising-agents",
      "en:artificial-flavouring",
      "en:flavouring",
      "en:emulsifier",
      "en:dark-chocolate",
      "en:chocolate",
      "en:iodised-salt",
      "en:salt",
      "en:nature-identical-flavouring",
      "en:e503ii",
      "en:e503",
      "en:e500ii",
      "en:e500",
      "en:e450i",
      "en:e450",
      "en:vanilla",
      "en:e471",
      "en:e322i",
      "en:e322",
      "en:from-soyabean",
    ],
    ingredients_lc: "en",
    ingredients_n: 27,
    ingredients_n_tags: ["27", "21-30"],
    ingredients_non_nutritive_sweeteners_n: 0,
    ingredients_original_tags: [
      "en:refined-wheat-flour",
      "en:sugar",
      "en:refined-palm-oil",
      "en:colour",
      "en:e150a",
      "en:e150a",
      "en:e150d",
      "en:e129",
      "en:starch",
      "en:cocoa-solids",
      "en:milk-solids-raising-agents",
      "en:artificial-flavouring",
      "en:emulsifier",
      "en:dark-chocolate",
      "en:iodised-salt",
      "en:nature-identical-flavouring",
      "en:refined-wheat-flour",
      "en:e503ii",
      "en:e500ii",
      "en:e450i",
      "en:vanilla",
      "en:chocolate",
      "en:e471",
      "en:e322i",
      "en:chocolate",
      "en:palm-oil",
      "en:from-soyabean",
    ],
    ingredients_percent_analysis: 1,
    ingredients_sweeteners_n: 0,
    ingredients_tags: [
      "en:refined-wheat-flour",
      "en:cereal",
      "en:flour",
      "en:wheat",
      "en:cereal-flour",
      "en:wheat-flour",
      "en:sugar",
      "en:added-sugar",
      "en:disaccharide",
      "en:refined-palm-oil",
      "en:oil-and-fat",
      "en:vegetable-oil-and-fat",
      "en:palm-oil-and-fat",
      "en:palm-oil",
      "en:colour",
      "en:e150a",
      "en:e150d",
      "en:e129",
      "en:starch",
      "en:cocoa-solids",
      "en:plant",
      "en:cocoa",
      "en:milk-solids-raising-agents",
      "en:artificial-flavouring",
      "en:flavouring",
      "en:emulsifier",
      "en:dark-chocolate",
      "en:chocolate",
      "en:iodised-salt",
      "en:salt",
      "en:nature-identical-flavouring",
      "en:e503ii",
      "en:e503",
      "en:e500ii",
      "en:e500",
      "en:e450i",
      "en:e450",
      "en:vanilla",
      "en:e471",
      "en:e322i",
      "en:e322",
      "en:from-soyabean",
    ],
    ingredients_text:
      "MAIDA (REFINED WHEAT FLOUR), SUGAR (32.8%), REFINED PALM OIL, COLOURS (INS 150a, INS 150c,\nINS 150d, INS 129], STARCH, COCOA SOLIDS (2.3%), MILK SOLIDS RAISING AGENTS [INS 503 (ii), INS 500 (ii), INS 450(i)], ARTIFICIAL FLAVOURING SUBSTANCES (VANILLA, CHOCOLATE), EMULSIFIERS [MONO - AND DI-GLYCERIDES OF FATTY ACIDS (FROM PALM OIL), LECITHIN (FROM SOYABEAN)], PLAIN CHOCOLATE (0.1%), IODIZED SALT AND NATURE IDENTICAL FLAVOURING SUBSTANCES (CHOCOLATE). CONTAINS WHEAT, MILK, SOY. MAY CONTAIN NUT, SULPHITE.",

    nova_groups_markers: {
      3: [
        ["ingredients", "en:salt"],
        ["ingredients", "en:starch"],
        ["ingredients", "en:sugar"],
        ["categories", "en:sweet-snacks"],
      ],
    },
    nova_groups_tags: ["en:4-ultra-processed-food-and-drink-products"],
    nucleotides_tags: [],
    nutrient_levels: {
      fat: "moderate",
      salt: "low",
      "saturated-fat": "high",
      sugars: "high",
    },
    nutrient_levels_tags: [
      "en:fat-in-moderate-quantity",
      "en:saturated-fat-in-high-quantity",
      "en:sugars-in-high-quantity",
      "en:salt-in-low-quantity",
    ],
    nutriments: {
      "added-sugars": 34.2,
      "added-sugars_100g": 34.2,
      "added-sugars_serving": 6.84,
      "added-sugars_unit": "g",
      "added-sugars_value": 34.2,
      carbohydrates: 73.5,
      carbohydrates_100g: 73.5,
      carbohydrates_serving: 14.7,
      carbohydrates_unit: "g",
      carbohydrates_value: 73.5,
      cholesterol: 0,
      cholesterol_100g: 0,
      cholesterol_serving: 0,
      cholesterol_unit: "g",
      cholesterol_value: 0,
      energy: 2004,
      "energy-kcal": 479,
      "energy-kcal_100g": 479,
      "energy-kcal_serving": 95.8,
      "energy-kcal_unit": "kcal",
      "energy-kcal_value": 479,
      "energy-kcal_value_computed": 479.4,
      energy_100g: 2004,
      energy_serving: 401,
      energy_unit: "kcal",
      energy_value: 479,
      fat: 18.2,
      fat_100g: 18.2,
      fat_serving: 3.64,
      fat_unit: "g",
      fat_value: 18.2,
      "fruits-vegetables-legumes-estimate-from-ingredients_100g": 0,
      "fruits-vegetables-legumes-estimate-from-ingredients_serving": 0,
      "fruits-vegetables-nuts-estimate-from-ingredients_100g": 0,
      "fruits-vegetables-nuts-estimate-from-ingredients_serving": 0,
      "nova-group": 4,
      "nova-group_100g": 4,
      "nova-group_serving": 4,
      "nutrition-score-fr": 24,
      "nutrition-score-fr_100g": 24,
      proteins: 5.4,
      proteins_100g: 5.4,
      proteins_serving: 1.08,
      proteins_unit: "g",
      proteins_value: 5.4,
      salt: 0.233,
      salt_100g: 0.233,
      salt_serving: 0.0466,
      salt_unit: "g",
      salt_value: 0.233,
      "saturated-fat": 8.8,
      "saturated-fat_100g": 8.8,
      "saturated-fat_serving": 1.76,
      "saturated-fat_unit": "g",
      "saturated-fat_value": 8.8,
      sodium: 0.0932,
      sodium_100g: 0.0932,
      sodium_serving: 0.0186,
      sodium_unit: "g",
      sodium_value: 0.0932,
      sugars: 36.4,
      sugars_100g: 36.4,
      sugars_serving: 7.28,
      sugars_unit: "g",
      sugars_value: 36.4,
      "trans-fat": 0.1,
      "trans-fat_100g": 0.1,
      "trans-fat_label": "Trans fat",
      "trans-fat_serving": 0.02,
      "trans-fat_unit": "g",
      "trans-fat_value": 0.1,
    },
    nutriscore: {
      2021: {
        category_available: 1,
        data: {
          energy: 2004,
          energy_points: 5,
          energy_value: 2004,
          fiber: 0,
          fiber_points: 0,
          fiber_value: 0,
          fruits_vegetables_nuts_colza_walnut_olive_oils: 0,
          fruits_vegetables_nuts_colza_walnut_olive_oils_points: 0,
          fruits_vegetables_nuts_colza_walnut_olive_oils_value: 0,
          is_beverage: 0,
          is_cheese: 0,
          is_fat: 0,
          is_water: 0,
          negative_points: 22,
          positive_points: 0,
          proteins: 5.4,
          proteins_points: 3,
          proteins_value: 5.4,
          saturated_fat: 8.8,
          saturated_fat_points: 8,
          saturated_fat_value: 8.8,
          sodium: 93.2,
          sodium_points: 1,
          sodium_value: 93.2,
          sugars: 36.4,
          sugars_points: 8,
          sugars_value: 36.4,
        },
        grade: "e",
        nutrients_available: 1,
        nutriscore_applicable: 1,
        nutriscore_computed: 1,
        score: 22,
      },
      2023: {
        category_available: 1,
        data: {
          components: {
            negative: [
              {
                id: "energy",
                points: 5,
                points_max: 10,
                unit: "kJ",
                value: 2004,
              },
              {
                id: "sugars",
                points: 10,
                points_max: 15,
                unit: "g",
                value: 36.4,
              },
              {
                id: "saturated_fat",
                points: 8,
                points_max: 10,
                unit: "g",
                value: 8.8,
              },
              {
                id: "salt",
                points: 1,
                points_max: 20,
                unit: "g",
                value: 0.23,
              },
            ],
            positive: [
              {
                id: "fiber",
                points: 0,
                points_max: 5,
                unit: "g",
                value: null,
              },
              {
                id: "fruits_vegetables_legumes",
                points: 0,
                points_max: 5,
                unit: "%",
                value: 0,
              },
            ],
          },
          count_proteins: 0,
          count_proteins_reason: "negative_points_greater_than_or_equal_to_11",
          is_beverage: 0,
          is_cheese: 0,
          is_fat_oil_nuts_seeds: 0,
          is_red_meat_product: 0,
          is_water: 0,
          negative_points: 24,
          negative_points_max: 55,
          positive_nutrients: ["fiber", "fruits_vegetables_legumes"],
          positive_points: 0,
          positive_points_max: 10,
        },
        grade: "e",
        nutrients_available: 1,
        nutriscore_applicable: 1,
        nutriscore_computed: 1,
        score: 24,
      },
    },
    nutriscore_2021_tags: ["e"],
    nutriscore_2023_tags: ["e"],
    nutriscore_data: {
      components: {
        negative: [
          {
            id: "energy",
            points: 5,
            points_max: 10,
            unit: "kJ",
            value: 2004,
          },
          {
            id: "sugars",
            points: 10,
            points_max: 15,
            unit: "g",
            value: 36.4,
          },
          {
            id: "saturated_fat",
            points: 8,
            points_max: 10,
            unit: "g",
            value: 8.8,
          },
          {
            id: "salt",
            points: 1,
            points_max: 20,
            unit: "g",
            value: 0.23,
          },
        ],
        positive: [
          {
            id: "fiber",
            points: 0,
            points_max: 5,
            unit: "g",
            value: null,
          },
          {
            id: "fruits_vegetables_legumes",
            points: 0,
            points_max: 5,
            unit: "%",
            value: 0,
          },
        ],
      },
      count_proteins: 0,
      count_proteins_reason: "negative_points_greater_than_or_equal_to_11",
      grade: "e",
      is_beverage: 0,
      is_cheese: 0,
      is_fat_oil_nuts_seeds: 0,
      is_red_meat_product: 0,
      is_water: 0,
      negative_points: 24,
      negative_points_max: 55,
      positive_nutrients: ["fiber", "fruits_vegetables_legumes"],
      positive_points: 0,
      positive_points_max: 10,
      score: 24,
    },
    nutriscore_grade: "e",
    nutriscore_score: 24,
    nutriscore_score_opposite: -24,
    nutriscore_tags: ["e"],
    nutriscore_version: "2023",
    nutrition_data: "on",
    nutrition_data_per: "100g",
    nutrition_data_prepared: "",
    nutrition_data_prepared_per: "100g",
    nutrition_grade_fr: "e",
    nutrition_grades: "e",
    nutrition_grades_tags: ["e"],
    nutrition_score_beverage: 0,
    nutrition_score_debug: "",
    nutrition_score_warning_fruits_vegetables_legumes_estimate_from_ingredients: 1,
    nutrition_score_warning_fruits_vegetables_legumes_estimate_from_ingredients_value: 0,
    nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients: 1,
    nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients_value: 0,
    nutrition_score_warning_no_fiber: 1,
    origin: "",
    origin_en: "",
    origins: "",
    origins_hierarchy: [],
    origins_lc: "en",
    origins_tags: [],
    other_nutritional_substances_tags: [],
    packaging_materials_tags: [],
    packaging_recycling_tags: [],
    packaging_shapes_tags: [],
    packaging_text: "",
    packaging_text_en: "",
    packagings: [],
    packagings_complete: 0,
    packagings_materials: {},
    photographers_tags: ["krishanti"],
    pnns_groups_1: "Sugary snacks",
    pnns_groups_1_tags: ["sugary-snacks", "known"],
    pnns_groups_2: "Biscuits and cakes",
    pnns_groups_2_tags: ["biscuits-and-cakes", "known"],
    popularity_key: 5,
    popularity_tags: [
      "at-least-5-scans-2024",
      "top-75-percent-scans-2024",
      "top-80-percent-scans-2024",
      "top-85-percent-scans-2024",
      "top-90-percent-scans-2024",
      "top-1000-in-scans-2024",
      "top-5000-in-scans-2024",
      "top-10000-in-scans-2024",
      "top-50000-in-scans-2024",
      "top-100000-in-scans-2024",
      "top-country-in-scans-2024",
      "at-least-5-in-scans-2024",
    ],
    product: {},
    product_name: "Bourbon Dark Fantasy Biscuit",
    product_name_en: "Bourbon Dark Fantasy Biscuit",
    product_quantity: 111.6,
    product_quantity_unit: "g",
    product_type: "food",
    purchase_places: "",
    purchase_places_tags: [],
    quantity: "111.6 g",
    removed_countries_tags: [],
    rev: 14,
    scans_n: 6,
    schema_version: 998,
    selected_images: {
      front: {
        display: {
          en: "https://images.openfoodfacts.net/images/products/890/172/501/6296/front_en.6.400.jpg",
        },
        small: {
          en: "https://images.openfoodfacts.net/images/products/890/172/501/6296/front_en.6.200.jpg",
        },
        thumb: {
          en: "https://images.openfoodfacts.net/images/products/890/172/501/6296/front_en.6.100.jpg",
        },
      },
      nutrition: {
        display: {
          en: "https://images.openfoodfacts.net/images/products/890/172/501/6296/nutrition_en.8.400.jpg",
        },
        small: {
          en: "https://images.openfoodfacts.net/images/products/890/172/501/6296/nutrition_en.8.200.jpg",
        },
        thumb: {
          en: "https://images.openfoodfacts.net/images/products/890/172/501/6296/nutrition_en.8.100.jpg",
        },
      },
    },
    serving_quantity: "20",
    serving_quantity_unit: "g",
    serving_size: "20 g",
    states:
      "en:to-be-completed, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-to-be-completed, en:origins-to-be-completed, en:categories-completed, en:brands-completed, en:packaging-to-be-completed, en:quantity-completed, en:product-name-completed, en:photos-to-be-validated, en:packaging-photo-to-be-selected, en:nutrition-photo-selected, en:ingredients-photo-to-be-selected, en:front-photo-selected, en:photos-uploaded",
    states_hierarchy: [
      "en:to-be-completed",
      "en:nutrition-facts-completed",
      "en:ingredients-completed",
      "en:expiration-date-to-be-completed",
      "en:packaging-code-to-be-completed",
      "en:characteristics-to-be-completed",
      "en:origins-to-be-completed",
      "en:categories-completed",
      "en:brands-completed",
      "en:packaging-to-be-completed",
      "en:quantity-completed",
      "en:product-name-completed",
      "en:photos-to-be-validated",
      "en:packaging-photo-to-be-selected",
      "en:nutrition-photo-selected",
      "en:ingredients-photo-to-be-selected",
      "en:front-photo-selected",
      "en:photos-uploaded",
    ],
    states_tags: [
      "en:to-be-completed",
      "en:nutrition-facts-completed",
      "en:ingredients-completed",
      "en:expiration-date-to-be-completed",
      "en:packaging-code-to-be-completed",
      "en:characteristics-to-be-completed",
      "en:origins-to-be-completed",
      "en:categories-completed",
      "en:brands-completed",
      "en:packaging-to-be-completed",
      "en:quantity-completed",
      "en:product-name-completed",
      "en:photos-to-be-validated",
      "en:packaging-photo-to-be-selected",
      "en:nutrition-photo-selected",
      "en:ingredients-photo-to-be-selected",
      "en:front-photo-selected",
      "en:photos-uploaded",
    ],
    stores: "",
    stores_tags: [],
    traces: "",
    traces_from_ingredients: "SULPHITE, SULPHITE, NUT",
    traces_from_user: "(en) ",
    traces_hierarchy: ["en:nuts", "en:sulphur-dioxide-and-sulphites"],
    traces_lc: "en",
    traces_tags: ["en:nuts", "en:sulphur-dioxide-and-sulphites"],
    unique_scans_n: 5,
    unknown_ingredients_n: 2,
    unknown_nutrients_tags: [],
    update_key: "sort",
    vitamins_tags: [],
    weighers_tags: [],
  },
  status: 1,
  status_verbose: "product found",
};
